[build-system]
requires = ["setuptools>=68"]
build-backend = "setuptools.build_meta"


[project]
name = "downloadyha"
version = "1.0.0"

description = "A simple YouTube downloader CLI"

readme = "README.md"

requires-python = ">=3.10"

dependencies = [
    "yt-dlp>=2026.8.19",
]


[project.optional-dependencies]
dev = [
    "pyinstaller>=6.0.0",
]
gui = [
    "customtkinter>=5.2.0",
    "pillow>=10.0.0",
]


[project.scripts]
downloadyha = "downloadyha.cli:main"
downloadyha-gui = "downloadyha.gui:main"


[tool.setuptools.packages.find]
where = ["src"]